### ISSUE TITLE
Issue regarding difference between Version 2.5.1 and 2.3.1, version 2.5.1 is not sending stats to elasticsearch with same config

### ISSUE THREAD

**Issue by hanaleung** [delirius325/jmeter-elasticsearch-backend-listener#36]
Hi,

I have an elastichsearch server setup in the same network with two different jmeter clients.
One of the clients was using elasticsearch-backend listener-2.3.1 and the other was freshly setup and downloaded 2.5.1 using PluginManager. The 2.3.1 client was running a testplan that was working fine and is able to send sample messages to my elasticsearch server but i've been unable to get it to work with 2.5.1

Is there a fundamental difference or changes in configuration that i may have missed that would result in stats being sent with the older version but not in the new version

Here is how my config looks like and i've been using the same testplan to test this:
![image](https://user-images.githubusercontent.com/39808956/49453803-d7682980-f7b1-11e8-945b-7762986241d8.png)
I'm basically trying to capture any messages with sample labels that look as follows:
R_/api/test

I've also tried copying the 2.3.1 jar directly to the lib/ext of the jmeter client that was running with 2.5.1 and it suddenly is able to send stats again with the exact same config.

I"m running the docker version 6.5.1 of elasticsearch:
"version": {
    "number": "6.5.1",
    "build_flavor": "default",
    "build_type": "tar",
    "build_hash": "8c58350",
    "build_date": "2018-11-16T02:22:42.182257Z",
    "build_snapshot": false,
    "lucene_version": "7.5.0",
    "minimum_wire_compatibility_version": "5.6.0",
    "minimum_index_compatibility_version": "5.0.0"
  }

Thank you for your time

**Comment by delirius325** [comment]
Hi!

I'm currently on vacation but I will get back to you as soon as I can! I find the issue rather strange!

Thanks

**Comment by hanaleung** [comment]
Thanks, I can continue to use 2.3.1 for the time being

**Comment by delirius325** [comment]
Still didn't thoroughly looked it up. But I'm curious to see your jmeter console and logs from both clients.

Would that be possible?

Thanks!

**Comment by hanaleung** [comment]
Hi,

Here is what i've gathered so far:

I'm using one client and i swapped between the different jars to get the logs, i made sure to delete the elasticsearch index between each try.

For 2.3.1, I can see the index created and messages get populated on my elasticSearch server

[2.3.1_INFO.log](https://github.com/delirius325/jmeter-elasticsearch-backend-listener/files/2668991/2.3.1_INFO.log)
[2.3.1_DEBUG.log](https://github.com/delirius325/jmeter-elasticsearch-backend-listener/files/2668992/2.3.1_DEBUG.log)

![image](https://user-images.githubusercontent.com/39808956/49824260-92ef0780-fd36-11e8-89a5-3b44278e1cd6.png)


For 2.5.1, i can see the index created but no messages ever get populated:

[2.5.1_INFO.log](https://github.com/delirius325/jmeter-elasticsearch-backend-listener/files/2668999/2.5.1_INFO.log)
[2.5.1_DEBUG.log](https://github.com/delirius325/jmeter-elasticsearch-backend-listener/files/2668998/2.5.1_DEBUG.log)

![image](https://user-images.githubusercontent.com/39808956/49824120-355abb00-fd36-11e8-8e9c-281e3a470145.png)

**Comment by delirius325** [comment]
Hey there,

So I looked at your logs and the one thing that differs from your Jmeter client using 2.5.1 is the following warninrg (which is actually an error): 

```
2018-12-11 11:07:36,685 WARN o.a.j.v.ViewResultsFullVisualizer: Error loading result renderer: org.apache.jmeter.visualizers.RenderInBrowser
java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:292) ~[?:?]
	at org.apache.jmeter.visualizers.ViewResultsFullVisualizer.createComboRender(ViewResultsFullVisualizer.java:462) [ApacheJMeter_components.jar:5.0 r1840935]
	at org.apache.jmeter.visualizers.ViewResultsFullVisualizer.createLeftPanel(ViewResultsFullVisualizer.java:430) [ApacheJMeter_components.jar:5.0 r1840935]
	at org.apache.jmeter.visualizers.ViewResultsFullVisualizer.init(ViewResultsFullVisualizer.java:342) [ApacheJMeter_components.jar:5.0 r1840935]
	at org.apache.jmeter.visualizers.ViewResultsFullVisualizer.<init>(ViewResultsFullVisualizer.java:147) [ApacheJMeter_components.jar:5.0 r1840935]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:488) ~[?:?]
	at java.lang.Class.newInstance(Class.java:558) [?:?]
	at org.apache.jmeter.gui.GuiPackage.getGuiFromCache(GuiPackage.java:405) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.gui.GuiPackage.getGui(GuiPackage.java:251) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.gui.GuiPackage.getGui(GuiPackage.java:222) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addComponent(JMeterTreeModel.java:157) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addSubTree(JMeterTreeModel.java:133) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addSubTree(JMeterTreeModel.java:125) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.gui.GuiPackage.addSubTree(GuiPackage.java:522) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.gui.action.Load.insertLoadedTree(Load.java:200) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.gui.action.Load.insertLoadedTree(Load.java:236) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.JMeter.startGui(JMeter.java:407) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.JMeter.start(JMeter.java:536) [ApacheJMeter_core.jar:5.0 r1840935]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.apache.jmeter.NewDriver.main(NewDriver.java:245) [ApacheJMeter.jar:5.0 r1840935]
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[?:?]
	... 27 more
```

This doesn't appear in the JMeter client using the 2.3.1 version of the ElasticSearch Backend Listener. That error isn't related to the plugin (first time I actually see it). Therefore, I'm wondering if you have something different in the two JMeter client used (whether it's installed plugin, config change, different versions of your JMX file/test plan).

Thanks,

**Comment by hanaleung** [comment]
I saw that error too and I thought it was unrelated to the plugin as well.

But the logs i sent you, I am testing with the same client, all i have done is swapped the jars from jmeter.backendlistener.elasticsearch-2.3.1.jar to jmeter.backendlistener.elasticsearch-2.5.1.jar. They are running the exact same test plan.

This particular client is using jmeter version 5.0 but i've had the same issue with 4.0 as well.

The java version is openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+11)
OpenJDK 64-Bit Server VM (build 9.0.4+11, mixed mode)

**Comment by Gabriel3G** [comment]
We had the same issue. It seems the "es.sample.filter" is broken in the newest release. We temporarily fixed it by removing the filter in our jmeter script.

**Comment by kevinwillox** [comment]
It seems to be an issue with the filter. Try without

**Comment by delirius325** [comment]
Hey everyone!

It's very possible that something changed with the way the functionality works. There has been many code refactoring between the two versions. I most likely introduced some sort of bug by mistake.

I'll take a look at it later tonight.

Thanks for the feedback!

**Comment by delirius325** [comment]
Issue is fixed in version 2.5.2. JAR is downloadable from the release section on this repository. Will soon be available from the JMeter Plugins Manager.

Thanks everyone,

**Comment by hanaleung** [comment]
I didn't want to open a new issue for this but I'm not sure where to comment on this for a closed issue but i picked up version 2.5.2 but I am still having trouble with the filter not working.

I'm trying to filter based on the string "R_/", for example, my REST api label is:

R_/rest/admin/v2/... etc..

but this doesn't get picked up as a valid sampler for the elasticsearch listener to log when i run the test.

When i remove the "R_/", all samples and their messages are logged as expected.

Is there something else i missed?

**Comment by delirius325** [comment]
Hi @hanaleung ,

I've released a SNAPSHOT attempting to solve the issue you're having with the filters. I'm pretty sure I found where the issue lied; but before I fully release a patch, I'd like you to try it first.

https://github.com/delirius325/jmeter-elasticsearch-backend-listener/releases/download/2.5.3-SNAPSHOT/jmeter.backendlistener.elasticsearch-2.5.3-SNAPSHOT.jar

Just download this JAR, put it in the `lib/ext` folder and make sure to delete any old versions of the plugin in that folder.

Thanks a lot,

**Comment by hanaleung** [comment]
Hello,

I just tried the SNAPSHOT and it looks like the filter is working again :)

Thanks for your help!

**Comment by delirius325** [comment]
Wonderful! :) 

@hanaleung : You have two options to be able to update the plugin in the future...

1. Rename the JAR to remove the `SNAPSHOT` from the name
2. Delete the JAR and redownload the plugin once the 2.5.3 version is out

Cheers!
