### ISSUE TITLE
Installed latest jar and now jmeter is throwing an error

### ISSUE THREAD

**Issue by Sunilcharlesedward** [delirius325/jmeter-elasticsearch-backend-listener#41]
Hi Anthony, Looking for some help, I am getting this error in Jmeter logs, was able to run it successfully before but needed BuildNumber in Elastic so installed the latest build 2.6.0 and now am getting this error as soon as I start a thread in jmeter

JMeter: Uncaught exception:

java.lang.NoSuchMethodError: org.elasticsearch.client.RestClient.performRequest(Lorg/elasticsearch/client/Request;)Lorg/elasticsearch/client/Response;

at io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticSearchMetricSender.createIndex(ElasticSearchMetricSender.java:71) ~[jmeter.backendlistener.elasticsearch-2.6.0.jar:?]

at io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticsearchBackendClient.setupTest(ElasticsearchBackendClient.java:104) ~[jmeter.backendlistener.elasticsearch-2.6.0.jar:?]

at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:337) ~[ApacheJMeter_components.jar:5.0 r1840935]

at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:292) ~[ApacheJMeter_components.jar:5.0 r1840935]

at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:215) ~[ApacheJMeter_core.jar:5.0 r1840935]

at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:384) ~[ApacheJMeter_core.jar:5.0 r1840935]

at java.lang.Thread.run(Unknown Source) [?:1.8.0_71

**Comment by delirius325** [comment]
Hi can I get more information please; what version of JMeter, screenshot of your test plan, etc.

**Comment by Sunilcharlesedward** [comment]
*Jmeter Version:* apache-jmeter-5.0 and apache-jmeter-5.1
*jmeter.backendlistener.elasticsearch-2.6.0.jar* placed in \lib\ext
directory
*rest-5.5.3.jar* placed in \lib directory

[image: image.png]





Previously when it was working i was using:
*JMeter_ElasticsearchListener.jar* extension placed in \lib\ext directory
*rest-5.5.3.jar* placed in \lib directory

and was getting these set of properties:
[image: image.png]

**Comment by Sunilcharlesedward** [comment]
Hi Anthony, did you get a chance to look at the screenshot and error ?

**Comment by delirius325** [comment]
Hi @Sunilcharlesedward,

The JAR you were using before `JMeter_ElasticSearchListener.jar` was very obsolete. What seems to be happening is that there are now conflicting JARs in your `lib`and `lib/ext` folders. What I suggest doing is:

1.  installing a fresh `JMeter`
2. install the `PluginsManager` to the fresh JMeter installation
3. launch JMeter from the fresh install and download all the plugins you use on a daily basis
4. launch your old JMeter and open up the test plan using the `ElasticSearch Backend Listener`
5. Remove the listener from the test plan
6. Save your test plan
7. Quit the old JMeter instance
8. In your fresh JMeter instance, open up your test plan
9. Add the backend listener
10. Choose the right implementation
11. Enter all of your details (url, port, etc.)
12. Launch your tests

By doing this, you'll be set and able to use the new version (which is far more performant and secure) of the ElasticSearch Backend Listener.
