### ISSUE TITLE
Exception while running the Test after adding the backend listener

### ISSUE THREAD

**Issue by jagadish2099** [delirius325/jmeter-elasticsearch-backend-listener#52]
After adding the backend listener and configuring the Kibana Host, I see the below error:

2019-06-18 17:29:48,083 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2019-06-18 17:29:48,083 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2019-06-18 17:29:48,084 INFO o.a.j.v.b.BackendListener: Backend Listener: Starting worker with class: class io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticsearchBackendClient and queue capacity: 5000
2019-06-18 17:29:48,085 INFO o.a.j.v.b.BackendListener: Backend Listener: Started  worker with class: class io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticsearchBackendClient
2019-06-18 17:29:48,085 ERROR o.a.j.JMeter: Uncaught exception: 
java.lang.IllegalStateException: Failed calling setupTest
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:339) ~[ApacheJMeter_components.jar:5.1.1 r1855137]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:292) ~[ApacheJMeter_components.jar:5.1.1 r1855137]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:206) ~[ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:381) ~[ApacheJMeter_core.jar:5.1.1 r1855137]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.IllegalStateException: Unable to connect to the ElasticSearch engine
	at io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticsearchBackendClient.setupTest(ElasticsearchBackendClient.java:119) ~[jmeter.backendlistener.elasticsearch-2.6.1.jar:?]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:337) ~[ApacheJMeter_components.jar:5.1.1 r1855137]
	... 4 more
Caused by: java.lang.NumberFormatException: For input string: "5601 "
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_211]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_211]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_211]
	at io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticsearchBackendClient.setupTest(ElasticsearchBackendClient.java:86) ~[jmeter.backendlistener.elasticsearch-2.6.1.jar:?]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:337) ~[ApacheJMeter_components.jar:5.1.1 r1855137]
	... 4 more

**Comment by jagadish2099** [comment]
On running the same test on command line, here is the log:

2019-06-18 20:05:23,662 INFO o.a.j.s.SampleResult: Note: Sample TimeStamps are START times
2019-06-18 20:05:23,663 INFO o.a.j.s.SampleResult: sampleresult.default.encoding is set to ISO-8859-1
2019-06-18 20:05:23,663 INFO o.a.j.s.SampleResult: sampleresult.useNanoTime=true
2019-06-18 20:05:23,663 INFO o.a.j.s.SampleResult: sampleresult.nanoThreadSleep=5000
2019-06-18 20:05:23,795 INFO o.a.j.JMeter: Creating summariser <summary>
2019-06-18 20:05:23,810 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2019-06-18 20:05:23,811 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2019-06-18 20:05:23,812 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2019-06-18 20:05:23,828 INFO o.a.j.e.u.CompoundVariable: Note: Function class names must contain the string: '.functions.'
2019-06-18 20:05:23,828 INFO o.a.j.e.u.CompoundVariable: Note: Function class names must not contain the string: '.gui.'
2019-06-18 20:05:24,992 INFO o.a.j.v.b.BackendListener: Backend Listener: Starting worker with class: class io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticsearchBackendClient and queue capacity: 5000
2019-06-18 20:05:24,995 INFO o.a.j.v.b.BackendListener: Backend Listener: Started  worker with class: class io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticsearchBackendClient
2019-06-18 20:05:24,996 ERROR o.a.j.JMeter: Uncaught exception: 
java.lang.IllegalStateException: Failed calling setupTest
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:339) ~[ApacheJMeter_components.jar:5.1.1 r1855137]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:292) ~[ApacheJMeter_components.jar:5.1.1 r1855137]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:206) ~[ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:381) ~[ApacheJMeter_core.jar:5.1.1 r1855137]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.IllegalStateException: Unable to connect to the ElasticSearch engine
	at io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticsearchBackendClient.setupTest(ElasticsearchBackendClient.java:119) ~[jmeter.backendlistener.elasticsearch-2.6.1.jar:?]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:337) ~[ApacheJMeter_components.jar:5.1.1 r1855137]
	... 4 more
Caused by: java.lang.NumberFormatException: For input string: "5601 "
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_211]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_211]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_211]
	at io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticsearchBackendClient.setupTest(ElasticsearchBackendClient.java:86) ~[jmeter.backendlistener.elasticsearch-2.6.1.jar:?]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:337) ~[ApacheJMeter_components.jar:5.1.1 r1855137]
	... 4 more
2019-06-18 20:05:25,008 INFO o.a.j.r.ResultCollector: Shutdown hook started
2019-06-18 20:05:25,008 INFO o.a.j.r.ResultCollector: Shutdown hook ended

**Comment by delirius325** [comment]
Hi @jagadish2099,

I see your mistake:

`Caused by: java.lang.NumberFormatException: For input string: "5601 "`

You have an extra white space after your port input. The plugin is unable to parse "5601 ", but will parse "5601". The error is on your part, granted the plugin should trim it. I'll add that in a new version.

Thanks,

**Comment by jagadish2099** [comment]
Got it sir, thanks its working fine now. Thank you so much.
