### ISSUE TITLE
Error - ERROR o.a.j.v.b.BackendListener

### ISSUE THREAD

**Issue by shuklagaurav23** [delirius325/jmeter-elasticsearch-backend-listener#72]
Hi,
I am getting following error in jmeter logs while trying to use 'backened listner' with Taurus. Any pointers would be very helpful.

**ERROR o.a.j.v.b.BackendListener: StandardJMeterEngine@58594a11-Backend Listener	Exception initialising: io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticsearchBackendClient
java.lang.ClassNotFoundException: io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticsearchBackendClient
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_221]
	at java.lang.Class.forName(Unknown Source)**

I am using following code in my Taurus YAML for fetching the plugin-
  plugins: 
  - jmeter.backendlistener.elasticsearch

**Comment by delirius325** [comment]
Hi there, I've never actually used Taurus so I couldn't say for sure what the problem is. However, what I am certain of is that the way your YAML file is configured isn't allowing Taurus to correctly fetch the plugin. The stacktrace clearly states that it basically could not find the class ElasticsearchBackendClient.

Sorry I can't be of much more help...

**Comment by delirius325** [comment]
Closing for inactivity.

**Comment by asos-gurpreetsingh** [comment]
Hi @shuklagaurav23 did you get it working ? i am also trying to use taurus yml to create tests and wondering how can i add a backend listener form yml
