### ISSUE TITLE
Getting java.lang error

### ISSUE THREAD

**Issue by debajyotichanda** [delirius325/jmeter-elasticsearch-backend-listener#75]
Hi Anthony,
We are using following plugin to send Jmeter metrics to Elasticserach : jmeter.backendlistener.elasticsearch-2.6.9.jar
Getting the following error in JMeter logs:
java.lang.NoSuchMethodError: org.elasticsearch.client.RestClient.performRequest(Lorg/elasticsearch/client/Request;)Lorg/elasticsearch/client/Response;
at io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticSearchMetricSender.createIndex(ElasticSearchMetricSender.java:95) ~[jmeter.backendlistener.elasticsearch-2.6.9.jar:?]
at io.github.delirius325.jmeter.backendlistener.elasticsearch.ElasticsearchBackendClient.setupTest(ElasticsearchBackendClient.java:139) ~[jmeter.backendlistener.elasticsearch-2.6.9.jar:?]
at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:349) ~[ApacheJMeter_components.jar:3.2 r1790748]
at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:302) ~[ApacheJMeter_components.jar:3.2 r1790748]
at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:218) ~[ApacheJMeter_core.jar:3.2 r1790748]
at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:388) ~[ApacheJMeter_core.jar:3.2 r1790748]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
2020-02-19 11:03:02,431 ERROR i.g.d.j.b.e.ElasticsearchBackend: ElasticSearch Backend Listener was unable to perform request to the ElasticSearch engine. Request reached timeout.
Our Jmeter version is : 3.2
Please suggest the needful. We are actually trying to use the SSL version of the ELK cluster. The old plugin version 2.2.5 is working just great.
Please see if you can help.
Thanks
DJ

**Comment by delirius325** [comment]
@debajyotichanda, please send me a list of plugins contained in your `lib/ext` folder. Also, send me a screenshot of your plugin's configuration. Thanks.

There are many things that changed from 2.2.5 to 2.6.9/2.6.10, chances are, configurations are not correct.

**Comment by debajyotichanda** [comment]
<img width="390" alt="Plugin" src="https://user-images.githubusercontent.com/39537073/74870282-7fbacd00-5327-11ea-9e11-cbf9f47e0ae3.png">

**Comment by debajyotichanda** [comment]
<img width="960" alt="JM_Config" src="https://user-images.githubusercontent.com/39537073/74870632-0d96b800-5328-11ea-883b-c0efe0010f00.png">

**Comment by debajyotichanda** [comment]
Thanks for looking into it.

**Comment by delirius325** [comment]
The issue is that you have 2 ES-backend-listener jars in your `lib/ext` folder. Remove the old one (2.2.5), then in your test plan, remove the Backend Listener and add it again, set it up, then everything should work!
