### ISSUE TITLE
Not able to run my tests, I get this below error:

### ISSUE THREAD

**Issue by nandakumargdg** [delirius325/jmeter-elasticsearch-backend-listener#87]
Please find the log present in jmeter.log below:

2020-06-02 01:57:01,139 INFO o.a.j.u.JMeterUtils: Setting Locale to en_EN
2020-06-02 01:57:01,148 INFO o.a.j.JMeter: Loading user properties from: /opt/apache-jmeter-5.2.1/bin/user.properties
2020-06-02 01:57:01,149 INFO o.a.j.JMeter: Loading system properties from: /opt/apache-jmeter-5.2.1/bin/system.properties
2020-06-02 01:57:01,149 INFO o.a.j.JMeter: Setting JMeter property: threads=1000
2020-06-02 01:57:01,149 INFO o.a.j.JMeter: Setting JMeter property: rampup=20
2020-06-02 01:57:01,149 INFO o.a.j.JMeter: Setting JMeter property: duration=6600
2020-06-02 01:57:01,149 INFO o.a.j.JMeter: Setting JMeter property: slugs=slugs.csv
2020-06-02 01:57:01,149 INFO o.a.j.JMeter: Setting JMeter property: slugs_with_quotes=slugs_with_quotes.csv
2020-06-02 01:57:01,149 INFO o.a.j.JMeter: Setting JMeter property: slugs_with_quotes_1=slugs_with_quotes_extra.csv
2020-06-02 01:57:01,149 INFO o.a.j.JMeter: Setting JMeter property: merchant_external_id=merchant_ids_for_get_merchant_prod.csv
2020-06-02 01:57:01,150 INFO o.a.j.JMeter: Setting JMeter property: merchant_ids_for_get_merchant_location=merchant_ids_for_get_merchant_location.csv
2020-06-02 01:57:01,150 INFO o.a.j.JMeter: Setting JMeter property: merchant_locations=merchant_locations.csv
2020-06-02 01:57:01,150 INFO o.a.j.JMeter: Setting JMeter property: merchant_location_external_id=merchant_locations_external_ids.csv
2020-06-02 01:57:01,150 INFO o.a.j.JMeter: Setting JMeter property: product_ids=product_ids.csv
2020-06-02 01:57:01,150 INFO o.a.j.JMeter: Setting JMeter property: product_ids_with_quotes=product_ids_with_quotes.csv
2020-06-02 01:57:01,150 INFO o.a.j.JMeter: Setting JMeter property: product_ids_with_quotes_1=product_ids_with_quotes_extra.csv
2020-06-02 01:57:01,150 INFO o.a.j.JMeter: Setting JMeter property: product_internal_id=product_internal_id.csv
2020-06-02 01:57:01,151 INFO o.a.j.JMeter: Copyright (c) 1998-2019 The Apache Software Foundation
2020-06-02 01:57:01,151 INFO o.a.j.JMeter: Version 5.2.1
2020-06-02 01:57:01,151 INFO o.a.j.JMeter: java.version=1.8.0_252
2020-06-02 01:57:01,152 INFO o.a.j.JMeter: java.vm.name=OpenJDK 64-Bit Server VM
2020-06-02 01:57:01,152 INFO o.a.j.JMeter: os.name=Linux
2020-06-02 01:57:01,152 INFO o.a.j.JMeter: os.arch=amd64
2020-06-02 01:57:01,152 INFO o.a.j.JMeter: os.version=4.15.0-1060-aws
2020-06-02 01:57:01,152 INFO o.a.j.JMeter: file.encoding=UTF-8
2020-06-02 01:57:01,152 INFO o.a.j.JMeter: java.awt.headless=null
2020-06-02 01:57:01,152 INFO o.a.j.JMeter: Max memory     =27489468416
2020-06-02 01:57:01,152 INFO o.a.j.JMeter: Available Processors =16
2020-06-02 01:57:01,155 INFO o.a.j.JMeter: Default Locale=English (EN)
2020-06-02 01:57:01,155 INFO o.a.j.JMeter: JMeter  Locale=English (EN)
2020-06-02 01:57:01,155 INFO o.a.j.JMeter: JMeterHome=/opt/apache-jmeter-5.2.1
2020-06-02 01:57:01,155 INFO o.a.j.JMeter: user.dir  =/opt/apache-jmeter-5.2.1/scripts/timor/cms
2020-06-02 01:57:01,155 INFO o.a.j.JMeter: PWD       =/opt/apache-jmeter-5.2.1/scripts/timor/cms
2020-06-02 01:57:01,156 INFO o.a.j.JMeter: IP: 10.250.4.21 Name: ip-10-250-4-21 FullName: ip-10-250-4-21.ap-southeast-1.compute.internal
2020-06-02 01:57:01,157 INFO o.a.j.JMeter: Setting property 'jmeter.reportgenerator.outputdir' to:'/opt/apache-jmeter-5.2.1/scripts/timor/cms/timorcms_external_k8_7.html'
2020-06-02 01:57:01,159 INFO o.a.j.s.FileServer: Default base='/opt/apache-jmeter-5.2.1/scripts/timor/cms'
2020-06-02 01:57:01,162 INFO o.a.j.s.FileServer: Set new base='/opt/apache-jmeter-5.2.1/scripts/timor/cms'
2020-06-02 01:57:01,249 INFO o.a.j.s.SaveService: Testplan (JMX) version: 2.2. Testlog (JTL) version: 2.2
2020-06-02 01:57:01,255 INFO o.a.j.s.SaveService: Using SaveService properties file encoding UTF-8
2020-06-02 01:57:01,258 INFO o.a.j.s.SaveService: Using SaveService properties version 5.0
2020-06-02 01:57:01,264 INFO o.a.j.s.SaveService: Loading file: timorcms.jmx
2020-06-02 01:57:01,311 INFO o.a.j.s.SampleResult: Note: Sample TimeStamps are START times
2020-06-02 01:57:01,311 INFO o.a.j.s.SampleResult: sampleresult.default.encoding is set to ISO-8859-1
2020-06-02 01:57:01,311 INFO o.a.j.s.SampleResult: sampleresult.useNanoTime=true
2020-06-02 01:57:01,311 INFO o.a.j.s.SampleResult: sampleresult.nanoThreadSleep=5000
2020-06-02 01:57:01,326 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/html is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2020-06-02 01:57:01,326 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for application/xhtml+xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2020-06-02 01:57:01,326 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for application/xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2020-06-02 01:57:01,326 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2020-06-02 01:57:01,326 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/vnd.wap.wml is org.apache.jmeter.protocol.http.parser.RegexpHTMLParser
2020-06-02 01:57:01,326 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/css is org.apache.jmeter.protocol.http.parser.CssParser
2020-06-02 01:57:01,340 INFO o.a.j.JMeter: Creating summariser <summary>
2020-06-02 01:57:01,344 INFO o.a.j.r.d.ReportGenerator: ReportGenerator will use for Parsing the separator: ','
2020-06-02 01:57:01,344 INFO o.a.j.r.d.ReportGenerator: Will generate report at end of test from  results file: timorcms_external_k8_7.jtl
2020-06-02 01:57:01,344 INFO o.a.j.r.d.ReportGenerator: Reading report generator properties from: /opt/apache-jmeter-5.2.1/bin/reportgenerator.properties
2020-06-02 01:57:01,345 INFO o.a.j.r.d.ReportGenerator: Merging with JMeter properties
2020-06-02 01:57:01,348 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.temp_dir' not found, using default value 'temp' instead.
2020-06-02 01:57:01,351 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.apdex_per_transaction' not found, using default value 'null' instead.
2020-06-02 01:57:01,351 INFO o.a.j.r.c.ReportGeneratorConfiguration: apdex_per_transaction is empty, not APDEX per transaction customization
2020-06-02 01:57:01,351 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.sample_filter' not found, using default value 'null' instead.
2020-06-02 01:57:01,351 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.report_title' not found, using default value 'null' instead.
2020-06-02 01:57:01,351 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.start_date' not found, using default value 'null' instead.
2020-06-02 01:57:01,351 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.end_date' not found, using default value 'null' instead.
2020-06-02 01:57:01,351 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.date_format' not found, using default value 'null' instead.
2020-06-02 01:57:01,351 INFO o.a.j.r.c.ReportGeneratorConfiguration: Will use date range start date: null, end date: null
2020-06-02 01:57:01,354 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.graph.totalTPS.exclude_controllers' not found, using default value 'false' instead.
2020-06-02 01:57:01,355 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.graph.activeThreadsOverTime.exclude_controllers' not found, using default value 'false' instead.
2020-06-02 01:57:01,355 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.graph.timeVsThreads.exclude_controllers' not found, using default value 'false' instead.
2020-06-02 01:57:01,355 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.graph.responseTimeDistribution.exclude_controllers' not found, using default value 'false' instead.
2020-06-02 01:57:01,355 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.graph.transactionsPerSecond.exclude_controllers' not found, using default value 'false' instead.
2020-06-02 01:57:01,355 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.graph.responseTimePercentiles.exclude_controllers' not found, using default value 'false' instead.
2020-06-02 01:57:01,355 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.graph.responseTimePercentilesOverTime.exclude_controllers' not found, using default value 'false' instead.
2020-06-02 01:57:01,355 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.graph.responseTimesOverTime.exclude_controllers' not found, using default value 'false' instead.
2020-06-02 01:57:01,355 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.graph.connectTimeOverTime.exclude_controllers' not found, using default value 'false' instead.
2020-06-02 01:57:01,356 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.graph.latenciesOverTime.exclude_controllers' not found, using default value 'false' instead.
2020-06-02 01:57:01,356 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.exporter.json.filters_only_sample_series' not found, using default value 'true' instead.
2020-06-02 01:57:01,356 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.exporter.json.series_filter' not found, using default value '' instead.
2020-06-02 01:57:01,356 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.exporter.json.show_controllers_only' not found, using default value 'false' instead.
2020-06-02 01:57:01,357 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.exporter.html.filters_only_sample_series' not found, using default value 'true' instead.
2020-06-02 01:57:01,357 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.exporter.html.series_filter' not found, using default value '' instead.
2020-06-02 01:57:01,357 INFO o.a.j.r.c.ReportGeneratorConfiguration: Property 'jmeter.reportgenerator.exporter.html.show_controllers_only' not found, using default value 'false' instead.
2020-06-02 01:57:01,360 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2020-06-02 01:57:01,361 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2020-06-02 01:57:01,361 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2020-06-02 01:57:01,365 INFO o.a.j.e.u.CompoundVariable: Note: Function class names must contain the string: '.functions.'
2020-06-02 01:57:01,365 INFO o.a.j.e.u.CompoundVariable: Note: Function class names must not contain the string: '.gui.'
2020-06-02 01:57:01,593 INFO o.a.j.v.b.BackendListener: Backend Listener: Starting worker with class: class org.apache.jmeter.visualizers.backend.graphite.GraphiteBackendListenerClient and queue capacity: 5000
2020-06-02 01:57:01,593 INFO o.a.j.v.b.BackendListener: Backend Listener: Started  worker with class: class org.apache.jmeter.visualizers.backend.graphite.GraphiteBackendListenerClient
2020-06-02 01:57:01,595 ERROR o.a.j.v.b.g.GraphiteBackendListenerClient: Error parsing percentile: 'jmeter.'
java.lang.NumberFormatException: For input string: "jmeter."
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:1.8.0_252]
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122) ~[?:1.8.0_252]
	at java.lang.Float.parseFloat(Float.java:451) ~[?:1.8.0_252]
	at java.lang.Float.valueOf(Float.java:416) ~[?:1.8.0_252]
	at org.apache.jmeter.visualizers.backend.graphite.GraphiteBackendListenerClient.initPercentileMaps(GraphiteBackendListenerClient.java:333) ~[ApacheJMeter_components.jar:5.2.1]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) [?:1.8.0_252]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) [?:1.8.0_252]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) [?:1.8.0_252]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) [?:1.8.0_252]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) [?:1.8.0_252]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) [?:1.8.0_252]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) [?:1.8.0_252]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) [?:1.8.0_252]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_252]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) [?:1.8.0_252]
	at org.apache.jmeter.visualizers.backend.graphite.GraphiteBackendListenerClient.setupTest(GraphiteBackendListenerClient.java:314) [ApacheJMeter_components.jar:5.2.1]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:326) [ApacheJMeter_components.jar:5.2.1]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:281) [ApacheJMeter_components.jar:5.2.1]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:206) [ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:381) [ApacheJMeter_core.jar:5.2.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
2020-06-02 01:57:01,598 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[StandardJMeterEngine,5,main]
java.lang.IllegalStateException: Failed calling setupTest
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:328) ~[ApacheJMeter_components.jar:5.2.1]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:281) ~[ApacheJMeter_components.jar:5.2.1]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:206) ~[ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:381) ~[ApacheJMeter_core.jar:5.2.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NullPointerException
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_252]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_252]
	at org.apache.jmeter.visualizers.backend.graphite.GraphiteBackendListenerClient.setupTest(GraphiteBackendListenerClient.java:315) ~[ApacheJMeter_components.jar:5.2.1]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:326) ~[ApacheJMeter_components.jar:5.2.1]

**Comment by delirius325** [comment]
Hi @nandakumargdg ,

According to your logs, this is an error relating to the Graphite Backend Listener, not the ElasticSearch backend listener 

> 2020-06-02 01:57:01,593 INFO o.a.j.v.b.BackendListener: Backend Listener: Starting worker with class: class **org.apache.jmeter.visualizers.backend.graphite.GraphiteBackendListenerClient** and queue capacity: 5000

If you want to use the ElasticSearch Backend Listener, you need to install it through the Plugins Manager and change the implementation of your Backend Listener element.

Thanks
